<?php

namespace app\controllers;

use Yii;
use yii\filters\Cors;
use yii\web\Controller;
use yii\helpers\Url;

use app\models\Photo;

class BaseController extends Controller
{

    public function beforeAction($action)
    {

//        if (Yii::$app->user->isGuest) {
//            return $this->redirect(['/site/index']);
//        }

        echo 'AAAA';
        $photo = Photo::find()->all();

        //Yii::setAlias('@example', 'http://example.com/');
        //echo Url::to('@example');

        //print_r($photo);
        echo Url::to('http://www.yiichina.com');

        print_r($this->getRoute());
        $this->redirect('http://www.yiichina.com');
        return false;
        //var_dump(parent::beforeAction($action));
        //return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}
